/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
static yyconst short int yy_accept[399] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   42,    1,    1,   21,   42,
       21,   20,   21,   42,   28,   42,   27,   28,   28,   28,
       28,   42,   34,   42,   34,   33,   34,   42,    0,    0,
       17,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,   27,    0,    0,    0,    0,    0,    0,   33,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       17,    0,   13,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   15,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,    0,    0,    0,    0,   29,    0,    0,
       35,    0,    0,    0,    0,   18,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   16,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   23,    0,   40,    0,   38,    0,    0,    0,    0,

        0,    0,   36,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   24,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       41,    0,   39,    0,    0,    0,    0,    0,    0,   37,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   11,   30,    0,    0,   23,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       19,    0,    0,    0,    0,    0,   32,    0,    0,    0,
        0,    0,   12,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        9,    0,    0,    0,   30,    0,    5,    0,    3,    0,
        0,    0,    0,    0,    0,    0,    0,   25,    0,    0,
        0,    0,    0,   10,    0,    0,    0,    0,   31,    0,
        6,    0,    4,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0,   26,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    2,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    7,    7,    8,    7,
        7,    6,    6,    6,    6,    7,    9,    7,   10,   11,
       12,   13,   14,    7,    7,    7,    7,    7,    6,   15,
       16,   17,    6,    7,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    7,    7,   27,   28,   29,   30,   31,
        7,   32,   33,   34,   35,   36,    7,    7,   37,    7,
        6,    6,    6,    6,    6,    6,   38,   39,   40,   41,

       42,   43,   44,   45,   46,    7,    7,   47,   48,   49,
       50,   51,    7,   52,   53,   54,   55,   56,   57,    7,
       58,   59,   60,    1,   60,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,    5,    6,    4,    7,    8,    9,    9,    3,    3,
        3,    7,    8,   10,    3,    3,    4,    3,   11,   12
    } ;

static yyconst short int yy_base[440] =
    {   0,
        0,    3,    4,    9, 1266, 1265,   61,  116, 1264, 1263,
       26,   27, 1262, 1261, 1276, 1283, 1283,  170, 1258, 1257,
     1283, 1283, 1221,    8,    3,   17, 1283, 1283, 1230, 1219,
     1224,   33, 1252, 1251, 1283, 1283, 1221,   37,    7,  208,
       21,   74, 1244, 1239, 1236, 1233,   86,   81, 1236, 1234,
       72,   53,   24,  108,  114, 1218, 1213, 1210, 1207,  112,
      127, 1210, 1208,   84,   11,  125, 1237, 1283, 1211,  138,
       54,   20, 1283, 1206, 1211, 1209,  145,   62, 1232, 1283,
     1189,  175,   85, 1217, 1196,  134,  254, 1223, 1218, 1215,
     1212,  254,  182, 1215, 1213,  270,  246,  129,  275,  280,

     1197, 1192, 1189, 1186,  279, 1189, 1187,  231,  113,  292,
       92,  296, 1283, 1212, 1203, 1195,  298, 1201, 1211, 1200,
     1203,  301,  303,  305, 1283, 1208, 1193,  163, 1190,  308,
     1182, 1173, 1165, 1171, 1181, 1170, 1173, 1153, 1138,  147,
      772,  780, 1283,  144,  776,  216,  763, 1283,  232,  771,
     1283,  261,  791,  770,  314, 1283,  321, 1283,  787,  778,
      762,  768,  778,  765,  324,  326,  332, 1283,  712,  697,
      183,  694,  334,  686,  677,  668,  674,  684,  673,  682,
      665,  293,  661,  696,  343,  675,  677,  345,  675,  686,
      679,  204,  350, 1283,  352, 1283,  688,  354,  676,  670,

      667,  356, 1283,  635,  638,  637,  649,  642,  640,  636,
      638,  361,  639,  363, 1283,  638,  372,  648,  626,  660,
      378,  652,  380,  628,  624,  382,  622,  631,  623,  384,
     1283,  387, 1283,  627,  389,  608,  604,  605,  391, 1283,
      572,  574,  573,  584,  576,  575,  571,  570,  400,  593,
      407, 1283,  242,  409,  411,  413,  596,  416,  592,  418,
      578,  573,  579,  576,  420,  550,  544,  525,  526,  427,
     1283,  512,  541,  429,  436,  438, 1283,  502,  479,  444,
      513,  446, 1283,  448,  453,  455,  513,  457,  511,  464,
      483,  479,  484,  485,  466,  458,  444,  433,  431,  473,

     1283,  439,  445,  475,  477,  482, 1283,  484, 1283,  418,
      486,  384,  390,  411,  491,  493,  495, 1283,  409,  502,
      376,  354,  510, 1283,  368,  381,  512,  514, 1283,  517,
     1283,  519, 1283,  348,  521,  316,  317,  325,  523,  323,
      530,  302,  539,  541, 1283,  543, 1283,  298,  546,  290,
      254,  258,  548,  253,  550,  243,  552,  219,  558,  561,
     1283,  170,  568,  165,  570,  574,  148,  577,  579,    8,
      581,  419,   28,  562,   23,  351,    8,  586,  593,  595,
       67,  597, 1283,  591,  616,  612,  117,    0,  645,  650,
      128,  654,  205,  671,  651,  325, 1283, 1283,  731,  743,

      755,  767,  779,  791,  803,  815,  826,  836,  846,  857,
      869,  881,  893,  905,  917,  929,  941,  953,  965,  977,
      989, 1001, 1013, 1025, 1037, 1049, 1061, 1073, 1085, 1097,
     1109, 1121, 1133, 1145, 1157, 1169, 1181, 1192, 1204
    } ;

static yyconst short int yy_def[440] =
    {   0,
      399,  399,  400,  400,  401,  401,  402,  402,  401,  401,
      403,  403,  401,  401,  398,  398,  398,  398,  404,  404,
      398,  398,  398,  398,  405,  405,  398,  398,  398,  398,
      398,  398,  406,  406,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  404,  398,  398,  398,
      407,  405,  398,  398,  398,  398,  398,  408,  406,  398,
      398,  398,  409,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  410,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  411,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  407,  398,  398,  398,  398,  408,  398,
      398,  409,  398,  398,  412,  398,  413,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  414,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  410,  410,  398,  398,  398,  398,  398,
      398,  398,  415,  398,  416,  398,  411,  411,  398,  398,

      398,  417,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  418,  398,  398,  398,  398,  398,  412,
      412,  413,  413,  398,  398,  398,  398,  398,  398,  419,
      398,  420,  398,  414,  414,  398,  398,  398,  421,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      422,  398,  398,  398,  398,  398,  415,  415,  416,  416,
      398,  398,  398,  417,  417,  398,  398,  398,  398,  423,
      398,  398,  418,  418,  398,  424,  398,  398,  398,  398,
      398,  425,  398,  398,  398,  398,  419,  419,  420,  420,
      398,  398,  398,  421,  421,  398,  398,  398,  398,  426,

      398,  398,  422,  422,  398,  427,  398,  428,  398,  398,
      398,  398,  398,  423,  423,  398,  429,  398,  424,  424,
      398,  398,  430,  398,  398,  425,  425,  431,  398,  432,
      398,  433,  398,  398,  398,  398,  398,  426,  426,  427,
      427,  428,  428,  434,  398,  435,  398,  429,  429,  398,
      398,  430,  430,  431,  431,  432,  432,  433,  433,  436,
      398,  434,  434,  435,  435,  398,  436,  436,  437,  437,
      437,  437,  398,  437,  398,  437,  398,  437,  398,  438,
      437,  439,  398,  438,  438,  438,  439,  439,  439,  438,
      439,  438,  439,  438,  439,  437,  398,    0,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398
    } ;

static yyconst short int yy_nxt[1344] =
    {   0,
       16,   16,   16,   16,   16,   16,   20,   73,   21,   70,
       70,   20,   71,   21,   18,   71,  383,   18,  398,   73,
       22,   73,  111,  111,   73,   22,  398,   84,   34,   34,
       35,   35,  372,   73,   77,   77,   73,   78,   82,   82,
       78,   83,   36,   36,   83,   21,   21,   85,   23,  129,
       21,   21,  373,   23,  379,   21,  141,  117,  143,   16,
       21,  143,   16,   26,  117,   27,  148,   35,   35,  148,
      377,   35,   35,  124,  124,  112,  112,   27,   37,   37,
      126,  375,  112,  112,   35,   35,  127,  128,  125,  151,
      113,  372,  151,  111,  111,   51,   51,  113,   51,   51,

       28,   28,   28,  114,   28,   29,   28,  119,  121,  112,
      112,  373,   28,   30,   28,  112,  112,   31,   26,  120,
       27,   51,   51,   51,  113,   51,  112,  112,  112,  112,
      113,  138,   27,  383,  130,  155,  155,  139,  140,   70,
       70,  113,   71,  113,  383,   71,   77,   77,  143,   78,
      156,  143,   78,  135,  172,   28,   28,   28,  183,   28,
       29,   28,   93,  131,  361,  136,   93,   28,   30,   28,
      391,  130,   31,   39,  137,  393,   82,   82,   40,   83,
      347,  117,   83,  157,  157,  117,  345,   41,   42,   43,
       44,   45,   46,  117,   47,   48,   49,  117,  158,   50,

       51,   93,   52,   53,   54,  256,  256,   41,   55,   56,
       57,   58,   59,   93,   60,   61,   62,  214,  214,   63,
       51,  383,   64,   65,   66,   86,   87,   88,   89,   90,
       91,  215,   92,   93,   94,  333,  148,   95,   96,  148,
       97,   98,   99,  305,  305,   86,  100,  101,  102,  103,
      104,  395,  105,   93,  106,  157,  157,  107,   96,  331,
      108,  109,  110,   96,   96,  151,   96,   96,  151,  329,
      158,  167,  167,  169,  324,  163,  157,  157,  180,  170,
      171,  157,  157,  159,  181,  182,  168,  164,   96,   96,
       96,  158,   96,  157,  157,  366,  158,  185,  185,  112,

      112,  173,  193,  193,  195,  195,  198,  198,  158,  202,
      202,  366,  113,  318,  113,  221,  221,  194,  309,  196,
      178,  125,  223,  223,  203,  230,  230,  232,  232,  174,
      156,   93,  179,  235,  235,  239,  239,  158,  173,  307,
      231,  301,  233,   93,  185,  185,  251,  251,  168,  372,
      240,  258,  258,  260,  260,  198,  198,  265,  265,  113,
       93,  252,  270,  270,  274,  274,  194,   93,  196,  373,
      125,   93,  203,  276,  276,  372,  271,  378,  215,  221,
      221,  223,  223,  282,  282,  288,  288,  277,  290,  290,
      235,  235,  295,  295,  156,  373,  158,  283,  283,   93,

      231,  300,  300,  233,  351,  168,  350,  240,  304,  304,
      306,  306,  308,  308,  256,  256,  301,  258,  258,  260,
      260,  265,  265,  252,  277,  307,  271,  309,  315,  315,
      274,  274,  194,  117,  196,  117,  203,  317,  317,  320,
      320,  117,  271,  372,  215,  323,  323,  327,  327,  328,
      328,  318,  374,  277,  330,  330,  332,  332,  288,  288,
      324,  252,  283,  373,  329,  290,  290,  295,  295,  331,
      117,  333,  335,  231,  339,  339,  304,  304,  305,  305,
      233,  337,  240,  341,  341,  343,  343,  344,  344,  301,
       93,  252,  315,  315,  346,  346,  349,  349,  307,  336,

      309,  240,  345,  320,  320,  335,  271,  334,  347,   93,
      318,  353,  353,  327,  327,  355,  355,  277,  357,  357,
      359,  359,  360,  360,  339,  339,  324,  233,  283,  231,
      329,  341,  341,  331,  325,  333,  322,  361,  321,  301,
      343,  343,  363,  363,  365,  365,  307,  349,  349,  353,
      353,  355,  355,  357,  357,  309,  215,  345,  347,  359,
      359,  318,  368,  368,  324,  316,  329,  311,  331,  363,
      363,  365,  365,  313,  333,  369,  369,  361,  368,  368,
      371,  371,  371,  371,  345,  347,  372,  380,  380,  376,
      117,  312,  203,  361,  382,  382,  385,  385,  389,  389,

      311,  310,  381,  372,  117,  372,  373,  381,  196,  383,
      372,  381,  194,  383,  302,  386,  299,  385,  385,  386,
      298,  297,  286,  373,  285,  373,  284,  296,  381,  280,
      373,  293,  381,  292,  291,  387,  386,  388,  388,  387,
      386,  388,  388,  168,  388,  390,  389,  389,  388,  286,
      388,  285,  389,  389,  388,  284,  387,  281,  388,  388,
      387,  383,  388,  388,  280,  388,  381,  397,  158,  388,
      381,  388,  385,  385,  386,  388,  156,  392,  386,  279,
      394,  278,  275,  272,  269,  268,  267,  396,  255,  254,
      253,  266,  249,  263,  387,  386,  388,  388,  387,  262,

      388,  388,  261,  388,  125,  255,  254,  388,  253,  388,
      250,  249,  113,  388,  248,  387,  247,  388,  388,  246,
      245,  244,  243,  226,  388,  242,  241,  238,  237,  236,
      388,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   67,  229,   67,   67,  228,  227,  226,   67,   67,

       67,   67,   67,   72,   72,   72,  225,  224,   72,  219,
      218,   72,  217,   72,   72,   79,  216,   79,   79,  213,
       79,   79,  212,   79,   79,  211,   79,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  370,  370,  370,  370,  370,  370,  370,  370,  210,
      209,  370,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  192,  208,  207,  206,
      188,  205,  204,  201,  200,  199,  192,  191,  190,  189,
      188,  187,  186,  166,  165,  177,   93,  176,  175,  166,
      165,  162,   93,  161,  160,  154,  153,  150,   80,  147,
      146,  145,  142,   68,  123,  122,  134,  117,  133,  132,
      123,  122,  118,  117,  116,  115,   81,   80,   80,   76,
       75,   74,   69,   68,   68,  398,   38,   38,   32,   32,
       24,   24,   15,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398
    } ;

static yyconst short int yy_chk[1344] =
    {   0,
        1,    1,    1,    2,    2,    2,    3,   25,    3,   24,
       24,    4,   24,    4,    1,   24,  388,    2,    0,   25,
        3,   26,   41,   41,   72,    4,    0,   39,   11,   12,
       11,   12,  370,   26,   32,   32,   72,   32,   38,   38,
       32,   38,   11,   12,   38,    3,    3,   39,    3,   53,
        4,    4,  370,    4,  377,    3,   65,   53,   71,    1,
        4,   71,    2,    7,   65,    7,   78,   11,   12,   78,
      375,   11,   12,   51,   51,   42,   42,    7,   11,   12,
       52,  373,   48,   48,   11,   12,   52,   52,   51,   83,
       42,  381,   83,  111,  111,   47,   47,   48,   47,   47,

        7,    7,    7,   42,    7,    7,    7,   47,   48,   54,
       54,  381,    7,    7,    7,   55,   55,    7,    8,   47,
        8,   60,   60,   60,   54,   60,   66,   66,   61,   61,
       55,   64,    8,  387,   54,   86,   86,   64,   64,   70,
       70,   66,   70,   61,  391,   70,   77,   77,  144,   77,
       86,  144,   77,   60,   98,    8,    8,    8,  109,    8,
        8,    8,   98,   55,  367,   60,  109,    8,    8,    8,
      387,   66,    8,   18,   61,  391,   82,   82,   18,   82,
      364,  128,   82,   93,   93,  140,  362,   18,   18,   18,
       18,   18,   18,  128,   18,   18,   18,  140,   93,   18,

       18,  171,   18,   18,   18,  192,  192,   18,   18,   18,
       18,   18,   18,  171,   18,   18,   18,  146,  146,   18,
       18,  393,   18,   18,   18,   40,   40,   40,   40,   40,
       40,  146,   40,   40,   40,  358,  149,   40,   40,  149,
       40,   40,   40,  253,  253,   40,   40,   40,   40,   40,
       40,  393,   40,   40,   40,   87,   87,   40,   40,  356,
       40,   40,   40,   92,   92,  152,   92,   92,  152,  354,
       87,   96,   96,   97,  352,   92,   99,   99,  108,   97,
       97,  100,  100,   87,  108,  108,   96,   92,  105,  105,
      105,   99,  105,  110,  110,  351,  100,  112,  112,  117,

      117,   99,  122,  122,  123,  123,  124,  124,  110,  130,
      130,  350,  112,  348,  117,  155,  155,  122,  342,  123,
      105,  124,  157,  157,  130,  165,  165,  166,  166,  100,
      155,  182,  105,  167,  167,  173,  173,  157,  110,  340,
      165,  338,  166,  182,  185,  185,  188,  188,  167,  396,
      173,  193,  193,  195,  195,  198,  198,  202,  202,  185,
      337,  188,  212,  212,  214,  214,  193,  336,  195,  396,
      198,  334,  202,  217,  217,  376,  212,  376,  214,  221,
      221,  223,  223,  226,  226,  230,  230,  217,  232,  232,
      235,  235,  239,  239,  221,  376,  223,  326,  226,  325,

      230,  249,  249,  232,  322,  235,  321,  239,  251,  251,
      254,  254,  255,  255,  256,  256,  249,  258,  258,  260,
      260,  265,  265,  251,  319,  254,  314,  255,  270,  270,
      274,  274,  258,  313,  260,  312,  265,  275,  275,  276,
      276,  310,  270,  372,  274,  280,  280,  282,  282,  284,
      284,  275,  372,  276,  285,  285,  286,  286,  288,  288,
      280,  303,  282,  372,  284,  290,  290,  295,  295,  285,
      302,  286,  299,  288,  300,  300,  304,  304,  305,  305,
      290,  298,  295,  306,  306,  308,  308,  311,  311,  300,
      297,  304,  315,  315,  316,  316,  317,  317,  306,  296,

      308,  294,  311,  320,  320,  293,  315,  292,  316,  291,
      317,  323,  323,  327,  327,  328,  328,  320,  330,  330,
      332,  332,  335,  335,  339,  339,  323,  289,  327,  287,
      328,  341,  341,  330,  281,  332,  279,  335,  278,  339,
      343,  343,  344,  344,  346,  346,  341,  349,  349,  353,
      353,  355,  355,  357,  357,  343,  273,  344,  346,  359,
      359,  349,  360,  360,  353,  272,  355,  269,  357,  363,
      363,  365,  365,  268,  359,  366,  366,  360,  368,  368,
      369,  369,  371,  371,  363,  365,  374,  378,  378,  374,
      267,  266,  264,  368,  379,  379,  380,  380,  382,  382,

      263,  262,  378,  369,  261,  371,  374,  384,  259,  379,
      378,  380,  257,  382,  250,  384,  248,  385,  385,  380,
      247,  246,  245,  369,  244,  371,  243,  242,  386,  241,
      378,  238,  385,  237,  236,  384,  386,  384,  384,  380,
      385,  380,  380,  234,  384,  386,  389,  389,  380,  229,
      384,  228,  395,  395,  380,  227,  386,  225,  386,  386,
      385,  389,  385,  385,  224,  386,  390,  395,  222,  385,
      392,  386,  394,  394,  390,  385,  220,  390,  392,  219,
      392,  218,  216,  213,  211,  210,  209,  394,  208,  207,
      206,  205,  204,  201,  390,  394,  390,  390,  392,  200,

      392,  392,  199,  390,  197,  191,  190,  392,  189,  390,
      187,  186,  184,  392,  183,  394,  181,  394,  394,  180,
      179,  178,  177,  176,  394,  175,  174,  172,  170,  169,
      394,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  400,  401,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  401,  401,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  404,  164,  404,  404,  163,  162,  161,  404,  404,

      404,  404,  404,  405,  405,  405,  160,  159,  405,  154,
      153,  405,  150,  405,  405,  406,  147,  406,  406,  145,
      406,  406,  142,  406,  406,  141,  406,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  413,  413,  413,  413,  413,  413,  413,

      413,  413,  413,  413,  413,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  422,  422,  422,  422,  422,  422,  422,  422,  422,
      422,  422,  422,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  427,  427,  427,  427,  427,  427,  427,  427,  427,
      427,  427,  427,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  428,  428,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  430,  430,  430,

      430,  430,  430,  430,  430,  430,  430,  430,  430,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  437,  437,  437,  437,  437,  437,  437,  437,  139,
      138,  437,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  137,  136,  135,  134,
      133,  132,  131,  129,  127,  126,  121,  120,  119,  118,
      116,  115,  114,  107,  106,  104,  103,  102,  101,   95,
       94,   91,   90,   89,   88,   85,   84,   81,   79,   76,
       75,   74,   69,   67,   63,   62,   59,   58,   57,   56,
       50,   49,   46,   45,   44,   43,   37,   34,   33,   31,
       30,   29,   23,   20,   19,   15,   14,   13,   10,    9,
        6,    5,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "LexAnalyser.l"
#define INITIAL 0
#line 2 "LexAnalyser.l"
#include<bits/stdc++.h>
#include<stdio.h>
#include<string.h>
#include "Parser.tab.h"

using namespace std;
int phcount=0;
char *findpos(const char* s,int len,int start);
char *findval(const char* s,int len,int start);
#define YY_STACK_USED 1
#define aInside 1

#define aAtt 2

#define imgInside 3

#define imgAtt 4

#define fontInside 5

#define fontAtt 6

#line 825 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 39 "LexAnalyser.l"

#line 989 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 399 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1283 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "LexAnalyser.l"
{
	if(yytext != "\n")
	{	yylval.value = yytext;
		return TEXT;
	}
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "LexAnalyser.l"
{
	yylval.value = "DOCTYPE ";
	return DOCTYPE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "LexAnalyser.l"
{
	yylval.value="HTMLOP ";
	return HTMLOP;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "LexAnalyser.l"
{
	yylval.value="HTMLCL ";
	return HTMLCL;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "LexAnalyser.l"
{
        yylval.value="HEADOP ";
        return HEADOP;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "LexAnalyser.l"
{
        yylval.value="HEADCL ";
        return HEADCL;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "LexAnalyser.l"
{
        yylval.value="TITLEOP ";
        return TITLEOP;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "LexAnalyser.l"
{
        yylval.value="TITLECL ";
        return TITLECL;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 74 "LexAnalyser.l"
{
        yylval.value="BODYOP ";
        return BODYOP;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "LexAnalyser.l"
{
        yylval.value="BODYCL ";
        return BODYCL;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 82 "LexAnalyser.l"
{
        yylval.value="DIVOP ";
        return DIVOP;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "LexAnalyser.l"
{
        yylval.value="DIVCL ";
        return DIVCL;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 90 "LexAnalyser.l"
{
        yylval.value=findpos(yytext,yyleng,1);
	phcount++;
	if(phcount==1){
		return BPHRASEOP;
	}
	else{
		return PHRASEOP;
	}
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "LexAnalyser.l"
{
	yylval.value=findpos(yytext,yyleng,2);
	phcount--;
	if(phcount==0)
		return BPHRASECL;
	else
		return PHRASECL;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 108 "LexAnalyser.l"
{
        yylval.value=findpos(yytext,yyleng,1);
        return GTPHOP;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "LexAnalyser.l"
{
        yylval.value=findpos(yytext,yyleng,2);
        return GTPHCL;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 116 "LexAnalyser.l"
{
	yy_push_state(aInside);
	yylval.value="AOP";
	return AOP;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "LexAnalyser.l"
{
	yylval.value="ACL";
	return ACL;
}
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 126 "LexAnalyser.l"
{
		yy_push_state(aAtt);
		yylval.value="HREF";
		yyless(yyleng-1);
		return ATTRIBUTE;
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 132 "LexAnalyser.l"
{
		yy_pop_state();
		yylval.value="AOPOP";
		return AOPOP;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 137 "LexAnalyser.l"
{}
	YY_BREAK


case 22:
YY_RULE_SETUP
#line 140 "LexAnalyser.l"
{
		yy_pop_state();
		yylval.value=findval(yytext,yyleng,1);
		return ATTRIBUTEVAL;
	}
	YY_BREAK

case 23:
YY_RULE_SETUP
#line 146 "LexAnalyser.l"
{
	yy_push_state(imgInside);
	yylval.value="IMGOP";
	return IMGOP;
}
	YY_BREAK

case 24:
YY_RULE_SETUP
#line 152 "LexAnalyser.l"
{
                yy_push_state(imgAtt);
                yylval.value="SRC";
                yyless(yyleng-1);
                return ATTRIBUTE;
        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 158 "LexAnalyser.l"
{
                yy_push_state(imgAtt);
                yylval.value="WIDTH";
                yyless(yyleng-1);
                return ATTRIBUTE;
        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 164 "LexAnalyser.l"
{
                yy_push_state(imgAtt);
                yylval.value="HEIGHT";
                yyless(yyleng-1);
                return ATTRIBUTE;
        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 170 "LexAnalyser.l"
{
                yy_pop_state();
                yylval.value="IMGCL";
                return IMGCL;
        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 175 "LexAnalyser.l"
{}
	YY_BREAK


case 29:
YY_RULE_SETUP
#line 178 "LexAnalyser.l"
{
                yy_pop_state();
                yylval.value=findval(yytext,yyleng,1);
                return ATTRIBUTEVAL;
        }
	YY_BREAK

case 30:
YY_RULE_SETUP
#line 184 "LexAnalyser.l"
{
        yy_push_state(fontInside);
        yylval.value="FONTOP";
	phcount++;
	if(phcount==1)
		return BPHRASEOP;
	else
		return FONTOP;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 193 "LexAnalyser.l"
{
        yylval.value="FONTCL";
	phcount--;
	if(phcount==0)
		return BPHRASECL;
	else
		return FONTCL;
}
	YY_BREAK

case 32:
YY_RULE_SETUP
#line 202 "LexAnalyser.l"
{
                yy_push_state(fontAtt);
                yylval.value="SIZE";
                yyless(yyleng-1);
                return ATTRIBUTE;
        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 208 "LexAnalyser.l"
{
                yy_pop_state();
                yylval.value="FONTOOP";
                return FONTOOP;
        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 213 "LexAnalyser.l"
{}
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 216 "LexAnalyser.l"
{
                yy_pop_state();
                yylval.value=findval(yytext,yyleng,1);
                return ATTRIBUTEVAL;
        }
	YY_BREAK

case 36:
YY_RULE_SETUP
#line 222 "LexAnalyser.l"
{
        yylval.value="ULOP ";
        return LOP;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 226 "LexAnalyser.l"
{
        yylval.value="ULCL ";
        return LCL;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 230 "LexAnalyser.l"
{
        yylval.value="OLOP ";
        return LOP;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 234 "LexAnalyser.l"
{
        yylval.value="OLCL ";
        return LCL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 238 "LexAnalyser.l"
{
        yylval.value="LIOP ";
        return LIOP;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 242 "LexAnalyser.l"
{
        yylval.value="LICL ";
        return LICL;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 247 "LexAnalyser.l"
ECHO;
	YY_BREAK
#line 1447 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(aInside):
case YY_STATE_EOF(aAtt):
case YY_STATE_EOF(imgInside):
case YY_STATE_EOF(imgAtt):
case YY_STATE_EOF(fontInside):
case YY_STATE_EOF(fontAtt):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 399 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 399 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 398);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 247 "LexAnalyser.l"


int yywrap(){
	return 1;
}
char *findpos(const char *s,int len,int start){
	int i=start,k=0;
	char *p=(char *)malloc(sizeof(char)*100);
	for(;i<len;i++){
		if((s[i]>=65 && s[i]<=90) || (s[i]>=97 && s[i]<=122))
			p[k++]=toupper(s[i]);
		else break;
	}
	p[k++]=32;
	p[k]=0;
	return p;
}
char *findval(const char *s,int len,int start){
        int i=start,k=0,flag=0;
        char *p=(char *)malloc(sizeof(char)*len);
        for(;i<len;i++){
		if(flag==1)
			p[k++]=s[i];
		if(flag==1 && (s[i]==34 || s[i]==39))
			break;
		if(flag==0 && (s[i]==34 || s[i]==39))
			flag=1;
        }
        p[k-1]=0;
        return p;
}

