#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from Parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "Parser.y"

#include<bits/stdc++.h>
#include<stdio.h>
#include<string.h>

using namespace std;
int i=0;

extern int yylex();
extern void yyerror(const char*);


#line 15 "Parser.y"
typedef union{
	char* object;
	char* value;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	DOCTYPE	258
#define	HTMLOP	259
#define	HTMLCL	260
#define	HEADOP	261
#define	HEADCL	262
#define	TITLEOP	263
#define	TITLECL	264
#define	BODYOP	265
#define	BODYCL	266
#define	BPHRASEOP	267
#define	BPHRASECL	268
#define	PHRASEOP	269
#define	PHRASECL	270
#define	GTPHOP	271
#define	GTPHCL	272
#define	TEXT	273
#define	AOPOP	274
#define	AOP	275
#define	ACL	276
#define	ATTRIBUTE	277
#define	ATTRIBUTEVAL	278
#define	DIVOP	279
#define	DIVCL	280
#define	IMGOP	281
#define	IMGCL	282
#define	FONTOP	283
#define	FONTOOP	284
#define	FONTCL	285
#define	LOP	286
#define	LCL	287
#define	LIOP	288
#define	LICL	289
#define	FIGOP	290
#define	FIGCL	291
#define	FIGCAPOP	292
#define	FIGCAPCL	293
#define	DLOP	294
#define	DLCL	295
#define	DTOP	296
#define	DTCL	297
#define	DDOP	298
#define	DDCL	299
#define	TABOP	300
#define	TABCL	301
#define	CAPOP	302
#define	CAPCL	303
#define	TROP	304
#define	TRCL	305
#define	THOP	306
#define	THCL	307
#define	TDOP	308
#define	TDCL	309
#define	BR	310
#define	COMMENT	311
#define	SPCHAR	312


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int DOCTYPE;
static const int HTMLOP;
static const int HTMLCL;
static const int HEADOP;
static const int HEADCL;
static const int TITLEOP;
static const int TITLECL;
static const int BODYOP;
static const int BODYCL;
static const int BPHRASEOP;
static const int BPHRASECL;
static const int PHRASEOP;
static const int PHRASECL;
static const int GTPHOP;
static const int GTPHCL;
static const int TEXT;
static const int AOPOP;
static const int AOP;
static const int ACL;
static const int ATTRIBUTE;
static const int ATTRIBUTEVAL;
static const int DIVOP;
static const int DIVCL;
static const int IMGOP;
static const int IMGCL;
static const int FONTOP;
static const int FONTOOP;
static const int FONTCL;
static const int LOP;
static const int LCL;
static const int LIOP;
static const int LICL;
static const int FIGOP;
static const int FIGCL;
static const int FIGCAPOP;
static const int FIGCAPCL;
static const int DLOP;
static const int DLCL;
static const int DTOP;
static const int DTCL;
static const int DDOP;
static const int DDCL;
static const int TABOP;
static const int TABCL;
static const int CAPOP;
static const int CAPCL;
static const int TROP;
static const int TRCL;
static const int THOP;
static const int THCL;
static const int TDOP;
static const int TDCL;
static const int BR;
static const int COMMENT;
static const int SPCHAR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,DOCTYPE=258
	,HTMLOP=259
	,HTMLCL=260
	,HEADOP=261
	,HEADCL=262
	,TITLEOP=263
	,TITLECL=264
	,BODYOP=265
	,BODYCL=266
	,BPHRASEOP=267
	,BPHRASECL=268
	,PHRASEOP=269
	,PHRASECL=270
	,GTPHOP=271
	,GTPHCL=272
	,TEXT=273
	,AOPOP=274
	,AOP=275
	,ACL=276
	,ATTRIBUTE=277
	,ATTRIBUTEVAL=278
	,DIVOP=279
	,DIVCL=280
	,IMGOP=281
	,IMGCL=282
	,FONTOP=283
	,FONTOOP=284
	,FONTCL=285
	,LOP=286
	,LCL=287
	,LIOP=288
	,LICL=289
	,FIGOP=290
	,FIGCL=291
	,FIGCAPOP=292
	,FIGCAPCL=293
	,DLOP=294
	,DLCL=295
	,DTOP=296
	,DTCL=297
	,DDOP=298
	,DDCL=299
	,TABOP=300
	,TABCL=301
	,CAPOP=302
	,CAPCL=303
	,TROP=304
	,TRCL=305
	,THOP=306
	,THCL=307
	,TDOP=308
	,TDCL=309
	,BR=310
	,COMMENT=311
	,SPCHAR=312


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::DOCTYPE=258;
const int YY_parse_CLASS::HTMLOP=259;
const int YY_parse_CLASS::HTMLCL=260;
const int YY_parse_CLASS::HEADOP=261;
const int YY_parse_CLASS::HEADCL=262;
const int YY_parse_CLASS::TITLEOP=263;
const int YY_parse_CLASS::TITLECL=264;
const int YY_parse_CLASS::BODYOP=265;
const int YY_parse_CLASS::BODYCL=266;
const int YY_parse_CLASS::BPHRASEOP=267;
const int YY_parse_CLASS::BPHRASECL=268;
const int YY_parse_CLASS::PHRASEOP=269;
const int YY_parse_CLASS::PHRASECL=270;
const int YY_parse_CLASS::GTPHOP=271;
const int YY_parse_CLASS::GTPHCL=272;
const int YY_parse_CLASS::TEXT=273;
const int YY_parse_CLASS::AOPOP=274;
const int YY_parse_CLASS::AOP=275;
const int YY_parse_CLASS::ACL=276;
const int YY_parse_CLASS::ATTRIBUTE=277;
const int YY_parse_CLASS::ATTRIBUTEVAL=278;
const int YY_parse_CLASS::DIVOP=279;
const int YY_parse_CLASS::DIVCL=280;
const int YY_parse_CLASS::IMGOP=281;
const int YY_parse_CLASS::IMGCL=282;
const int YY_parse_CLASS::FONTOP=283;
const int YY_parse_CLASS::FONTOOP=284;
const int YY_parse_CLASS::FONTCL=285;
const int YY_parse_CLASS::LOP=286;
const int YY_parse_CLASS::LCL=287;
const int YY_parse_CLASS::LIOP=288;
const int YY_parse_CLASS::LICL=289;
const int YY_parse_CLASS::FIGOP=290;
const int YY_parse_CLASS::FIGCL=291;
const int YY_parse_CLASS::FIGCAPOP=292;
const int YY_parse_CLASS::FIGCAPCL=293;
const int YY_parse_CLASS::DLOP=294;
const int YY_parse_CLASS::DLCL=295;
const int YY_parse_CLASS::DTOP=296;
const int YY_parse_CLASS::DTCL=297;
const int YY_parse_CLASS::DDOP=298;
const int YY_parse_CLASS::DDCL=299;
const int YY_parse_CLASS::TABOP=300;
const int YY_parse_CLASS::TABCL=301;
const int YY_parse_CLASS::CAPOP=302;
const int YY_parse_CLASS::CAPCL=303;
const int YY_parse_CLASS::TROP=304;
const int YY_parse_CLASS::TRCL=305;
const int YY_parse_CLASS::THOP=306;
const int YY_parse_CLASS::THCL=307;
const int YY_parse_CLASS::TDOP=308;
const int YY_parse_CLASS::TDCL=309;
const int YY_parse_CLASS::BR=310;
const int YY_parse_CLASS::COMMENT=311;
const int YY_parse_CLASS::SPCHAR=312;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		253
#define	YYFLAG		-32768
#define	YYNTBASE	58

#define YYTRANSLATE(x) ((unsigned)(x) <= 312 ? yytranslate[x] : 86)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     6,     9,    14,    18,    24,    29,    34,    38,
    42,    45,    48,    52,    55,    57,    61,    64,    67,    70,
    73,    76,    79,    83,    86,    89,    92,    95,    98,   101,
   103,   105,   107,   109,   111,   115,   121,   125,   130,   137,
   142,   144,   147,   150,   152,   154,   158,   162,   166,   172,
   178,   181,   186,   191,   196,   203,   210,   212,   215,   219,
   224,   226,   229,   233,   238,   240,   243,   247,   250,   257,
   262,   266,   272,   276,   279,   285,   290,   294,   297,   300,
   302,   307,   311,   315,   318,   320,   322,   325,   330,   334,
   338,   341,   345,   348,   352,   355,   357,   360,   362,   364,
   370,   375,   380,   384,   389,   393,   398,   402,   405,   409,
   412,   416,   418,   420,   423,   428,   434,   438,   442,   444,
   447,   449,   454,   458,   463,   466,   468,   474,   479,   485,
   489,   492,   495,   497,   499,   503,   507,   510,   515,   520,
   525,   532,   536,   542,   545,   550,   552
};

static const short yyrhs[] = {     3,
     0,     3,     4,     5,     0,     4,     5,     0,     3,     4,
    59,     5,     0,     4,    59,     5,     0,     3,     4,    59,
    62,     5,     0,     4,    59,    62,     5,     0,     3,     4,
    62,     5,     0,     4,    62,     5,     0,     6,    60,     7,
     0,     6,     7,     0,     8,     9,     0,     8,    61,     9,
     0,    61,    18,     0,    18,     0,    10,    63,    11,     0,
    10,    11,     0,    12,    74,     0,    16,    73,     0,    20,
    72,     0,    24,    71,     0,    26,    76,     0,    26,    76,
    63,     0,    28,    77,     0,    31,    79,     0,    35,    81,
     0,    39,    83,     0,    45,    66,     0,    64,    63,     0,
    64,     0,    61,     0,    56,     0,    65,     0,    55,     0,
    47,    67,    46,     0,    47,    67,    49,    68,    46,     0,
    49,    68,    46,     0,    47,    67,    46,    63,     0,    47,
    67,    49,    68,    46,    63,     0,    49,    68,    46,    63,
     0,    46,     0,    46,    63,     0,    63,    48,     0,    48,
     0,    50,     0,    51,    69,    50,     0,    53,    70,    50,
     0,    50,    49,    68,     0,    51,    69,    50,    49,    68,
     0,    53,    70,    50,    49,    68,     0,    64,    50,     0,
    64,    51,    69,    50,     0,    64,    53,    70,    50,     0,
    64,    50,    49,    68,     0,    64,    51,    69,    50,    49,
    68,     0,    64,    53,    70,    50,    49,    68,     0,    52,
     0,    63,    52,     0,    52,    51,    69,     0,    63,    52,
    51,    69,     0,    54,     0,    63,    54,     0,    54,    53,
    70,     0,    63,    54,    53,    70,     0,    25,     0,    25,
    63,     0,    63,    25,    63,     0,    63,    25,     0,    22,
    23,    19,    63,    21,    63,     0,    19,    63,    21,    63,
     0,    19,    21,    63,     0,    22,    23,    19,    63,    21,
     0,    19,    63,    21,     0,    19,    21,     0,    22,    23,
    19,    21,    63,     0,    22,    23,    19,    21,     0,    75,
    17,    63,     0,    17,    63,     0,    75,    17,     0,    17,
     0,    12,    74,    17,    63,     0,    12,    74,    17,     0,
    75,    13,    63,     0,    13,    63,     0,    13,     0,    78,
     0,    75,    13,     0,    75,    14,    75,    15,     0,    75,
    14,    15,     0,    14,    75,    15,     0,    14,    15,     0,
    75,    26,    76,     0,    75,    78,     0,    75,    28,    78,
     0,    28,    78,     0,    78,     0,    26,    76,     0,    61,
     0,    64,     0,    75,    14,    75,    15,    64,     0,    75,
    14,    15,    64,     0,    14,    75,    15,    64,     0,    14,
    15,    64,     0,    75,    26,    76,    64,     0,    75,    78,
    64,     0,    75,    28,    78,    64,     0,    28,    78,    64,
     0,    78,    64,     0,    26,    76,    64,     0,    61,    64,
     0,    22,    23,    76,     0,    27,     0,    78,     0,    78,
    63,     0,    22,    23,    29,    30,     0,    22,    23,    29,
    75,    30,     0,    29,    75,    30,     0,    33,    80,    79,
     0,    32,     0,    63,    34,     0,    34,     0,    63,    37,
    82,    36,     0,    37,    82,    36,     0,    37,    82,    63,
    36,     0,    63,    36,     0,    36,     0,    63,    37,    82,
    36,    63,     0,    37,    82,    36,    63,     0,    37,    82,
    63,    36,    63,     0,    63,    36,    63,     0,    36,    63,
     0,    63,    38,     0,    38,     0,    40,     0,    24,    71,
    40,     0,    41,    84,    40,     0,    40,    63,     0,    24,
    71,    40,    63,     0,    41,    84,    40,    63,     0,    63,
    42,    43,    85,     0,    63,    42,    43,    85,    41,    84,
     0,    42,    43,    85,     0,    42,    43,    85,    41,    84,
     0,    63,    44,     0,    63,    44,    43,    85,     0,    44,
     0,    44,    43,    85,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    57,    58,    59,    60,    61,    62,    63,    64,    65,    68,
    70,    74,    75,    78,    79,    82,    83,    86,    87,    88,
    89,    90,    91,    92,    93,    94,    95,    96,    97,    98,
    99,   102,   103,   106,   109,   110,   111,   112,   113,   114,
   115,   116,   119,   120,   123,   124,   125,   126,   127,   128,
   129,   130,   131,   132,   133,   134,   137,   138,   139,   140,
   143,   144,   145,   146,   149,   150,   151,   152,   155,   156,
   157,   158,   159,   160,   161,   162,   165,   166,   167,   168,
   169,   170,   173,   174,   175,   176,   177,   180,   181,   182,
   183,   184,   185,   186,   187,   188,   189,   190,   191,   192,
   193,   194,   195,   196,   197,   198,   199,   200,   201,   202,
   205,   206,   209,   210,   213,   214,   215,   218,   219,   222,
   223,   226,   227,   228,   229,   230,   231,   232,   233,   234,
   235,   238,   239,   242,   243,   244,   245,   246,   247,   250,
   251,   252,   253,   256,   257,   258,   259
};

static const char * const yytname[] = {   "$","error","$illegal.","DOCTYPE",
"HTMLOP","HTMLCL","HEADOP","HEADCL","TITLEOP","TITLECL","BODYOP","BODYCL","BPHRASEOP",
"BPHRASECL","PHRASEOP","PHRASECL","GTPHOP","GTPHCL","TEXT","AOPOP","AOP","ACL",
"ATTRIBUTE","ATTRIBUTEVAL","DIVOP","DIVCL","IMGOP","IMGCL","FONTOP","FONTOOP",
"FONTCL","LOP","LCL","LIOP","LICL","FIGOP","FIGCL","FIGCAPOP","FIGCAPCL","DLOP",
"DLCL","DTOP","DTCL","DDOP","DDCL","TABOP","TABCL","CAPOP","CAPCL","TROP","TRCL",
"THOP","THCL","TDOP","TDCL","BR","COMMENT","SPCHAR","st","head","title","text",
"body","flow","misc","br","table","caption","tr","th","td","div","atag","gtph",
"phraseopen","phrases","img","fontsub","font","list","listitem","figure","figcap",
"dl","dt","dd",""
};
#endif

static const short yyr1[] = {     0,
    58,    58,    58,    58,    58,    58,    58,    58,    58,    59,
    59,    60,    60,    61,    61,    62,    62,    63,    63,    63,
    63,    63,    63,    63,    63,    63,    63,    63,    63,    63,
    63,    64,    64,    65,    66,    66,    66,    66,    66,    66,
    66,    66,    67,    67,    68,    68,    68,    68,    68,    68,
    68,    68,    68,    68,    68,    68,    69,    69,    69,    69,
    70,    70,    70,    70,    71,    71,    71,    71,    72,    72,
    72,    72,    72,    72,    72,    72,    73,    73,    73,    73,
    73,    73,    74,    74,    74,    74,    74,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    75,    75,    75,    75,    75,    75,    75,    75,    75,    75,
    76,    76,    77,    77,    78,    78,    78,    79,    79,    80,
    80,    81,    81,    81,    81,    81,    81,    81,    81,    81,
    81,    82,    82,    83,    83,    83,    83,    83,    83,    84,
    84,    84,    84,    85,    85,    85,    85
};

static const short yyr2[] = {     0,
     1,     3,     2,     4,     3,     5,     4,     4,     3,     3,
     2,     2,     3,     2,     1,     3,     2,     2,     2,     2,
     2,     2,     3,     2,     2,     2,     2,     2,     2,     1,
     1,     1,     1,     1,     3,     5,     3,     4,     6,     4,
     1,     2,     2,     1,     1,     3,     3,     3,     5,     5,
     2,     4,     4,     4,     6,     6,     1,     2,     3,     4,
     1,     2,     3,     4,     1,     2,     3,     2,     6,     4,
     3,     5,     3,     2,     5,     4,     3,     2,     2,     1,
     4,     3,     3,     2,     1,     1,     2,     4,     3,     3,
     2,     3,     2,     3,     2,     1,     2,     1,     1,     5,
     4,     4,     3,     4,     3,     4,     3,     2,     3,     2,
     3,     1,     1,     2,     4,     5,     3,     3,     1,     2,
     1,     4,     3,     4,     2,     1,     5,     4,     5,     3,
     2,     2,     1,     1,     3,     3,     2,     4,     4,     4,
     6,     3,     5,     2,     4,     1,     3
};

static const short yydefact[] = {     0,
     1,     0,     0,     3,     0,     0,     0,     0,     2,     0,
     0,    11,     0,     0,    17,     0,     0,    15,     0,     0,
     0,     0,     0,     0,     0,     0,    34,    32,    31,     0,
    30,    33,     5,     0,     9,     4,     0,     8,    12,     0,
    10,    85,     0,     0,     0,     0,     0,    98,    99,    18,
     0,    86,     0,    80,    19,     0,    96,     0,     0,    20,
    65,     0,    21,     0,   112,    22,    24,   113,   119,     0,
    25,   126,     0,     0,    26,     0,   134,     0,    27,    41,
     0,     0,    28,    14,    16,    29,     7,     6,    13,    84,
    91,     0,     0,    97,    95,     0,   110,    87,     0,     0,
     0,    93,   108,     0,    78,    79,    74,     0,     0,    66,
    68,     0,    23,   114,   121,     0,     0,   131,   133,     0,
     0,   125,     0,     0,   137,     0,     0,     0,    42,    44,
     0,     0,    45,     0,     0,     0,     0,   103,    90,     0,
   109,   107,   117,    83,    89,     0,    92,    94,   105,    82,
    77,    71,    73,     0,    67,   111,   120,   118,   132,   123,
     0,   130,     0,   135,     0,     0,   136,    43,    35,     0,
     0,    57,     0,     0,    61,     0,     0,    51,     0,     0,
    37,   102,   115,     0,   101,    88,   104,   106,    81,    70,
    76,     0,   128,   124,   122,   138,   146,     0,   142,     0,
   139,    38,     0,    48,     0,    58,    46,     0,    62,    47,
     0,     0,     0,    40,   116,   100,    75,    72,   129,   127,
     0,   144,     0,   140,    36,    59,     0,     0,    63,     0,
     0,    54,    52,    53,    69,   147,     0,   143,     0,    39,
    60,    49,    64,    50,     0,     0,   145,   141,    55,    56,
     0,     0,     0
};

static const short yydefgoto[] = {   251,
     7,    14,    29,     8,   173,    31,    32,    83,   132,   137,
   174,   177,    63,    60,    55,    50,    51,    66,    67,   102,
    71,   117,    75,   121,    79,   128,   199
};

static const short yypact[] = {   120,
     7,    98,   115,-32768,   179,   216,    41,     8,-32768,   147,
    37,-32768,    21,    42,-32768,    84,   589,-32768,   160,   283,
   146,    18,   145,   257,   -18,   144,-32768,-32768,    -3,    47,
   574,-32768,-32768,    64,-32768,-32768,    68,-32768,-32768,    25,
-32768,   574,   499,    56,   146,    18,   629,   -11,-32768,-32768,
   105,   170,    84,   574,-32768,   194,   174,   125,    63,-32768,
   574,    65,-32768,    76,-32768,   574,-32768,   574,-32768,   317,
-32768,   574,   343,   242,-32768,   283,   574,   377,-32768,   574,
   411,    38,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   174,   234,    78,   174,   174,    54,-32768,   574,   606,   146,
    18,   174,-32768,    97,-32768,   574,   574,   101,   111,-32768,
   574,   146,-32768,-32768,-32768,   104,   145,-32768,-32768,    94,
   429,   574,   343,   102,-32768,   112,   123,   129,-32768,-32768,
   157,   151,   158,   463,   481,   153,   149,-32768,   174,   624,
-32768,-32768,-32768,-32768,   174,   392,   174,   174,-32768,   574,
-32768,-32768,   574,   522,-32768,-32768,-32768,-32768,-32768,   574,
   173,-32768,   199,   574,   540,   196,   574,-32768,   574,    38,
    38,   186,   189,   193,   192,   203,   215,   219,   463,   481,
   574,-32768,-32768,   224,-32768,   174,-32768,-32768,-32768,-32768,
   574,   249,-32768,   574,   574,-32768,   231,   232,   239,   540,
-32768,-32768,   236,-32768,   463,   233,   237,   481,   238,   248,
    38,   250,   254,-32768,-32768,-32768,-32768,   574,-32768,-32768,
   540,   244,   377,   265,   574,-32768,   463,    38,-32768,   481,
    38,-32768,   261,   266,-32768,-32768,   540,-32768,   377,-32768,
-32768,-32768,-32768,-32768,    38,    38,-32768,-32768,-32768,-32768,
   298,   316,-32768
};

static const short yypgoto[] = {-32768,
   314,-32768,   -12,     9,    -6,   119,-32768,-32768,-32768,  -150,
  -177,  -171,   243,-32768,-32768,   267,   -14,   -35,-32768,    10,
   204,-32768,-32768,   200,-32768,  -215,  -183
};


#define	YYLAST		685


static const short yytable[] = {    30,
    40,   212,    56,    48,    48,    76,    84,   238,   213,    94,
     3,    11,    35,    62,    84,    34,   224,    74,    37,   203,
   204,    77,    78,   248,    86,    52,    57,   226,    92,    39,
    48,    68,    96,    89,    48,    90,   229,   236,    18,    44,
    48,    38,    84,    27,    28,    33,    47,   105,    41,   241,
     6,   108,    57,   247,   110,    95,    57,    85,   243,   113,
   232,   114,    52,   116,   147,   118,   120,    99,    87,    62,
   125,   127,    88,   129,   131,    44,   156,   242,    93,   100,
   244,   101,    47,   143,   146,   109,    48,   133,   134,   111,
   135,   144,    27,    28,   249,   250,    42,    43,   112,   151,
   152,    18,     4,     5,   155,    44,   140,     6,    57,    45,
   148,    46,    47,   150,   161,   162,   120,    98,    99,     9,
     5,   153,     1,     2,     6,   184,    44,    48,   176,   154,
   100,   159,   101,    47,    49,    49,    16,   157,    27,    28,
    17,   164,    18,   189,    19,   107,   190,   192,    20,    57,
    21,    36,    22,   193,   165,    23,     6,   196,   198,    24,
   201,    49,   202,    25,   166,    49,    97,    64,   167,    26,
   103,    49,    65,   176,   214,   103,    69,    70,    58,    27,
    28,    59,   -96,   -96,   217,    12,    13,   219,   220,    80,
    81,   -96,    82,   198,   181,   -96,   169,   -96,   -96,   170,
   136,   176,   178,   179,   168,   180,   171,    99,   194,   138,
   106,   235,   141,   142,   198,    44,   127,    49,   240,   100,
   149,   101,    47,   176,    27,    28,    15,    16,    27,    28,
   198,    17,   127,    18,   195,    19,   205,    99,   200,    20,
   206,    21,   207,    22,   208,    44,    23,    99,   139,   100,
    24,   101,    47,   215,    25,    44,   209,   182,    49,   100,
    26,   101,    47,   185,   210,   187,   188,   211,    16,   218,
    27,    28,    17,   221,    18,   222,    19,   122,   123,   223,
    20,   225,    21,   227,    22,   228,   237,    23,   136,   136,
   230,    24,    72,    73,    16,    25,   231,   252,    17,   233,
    18,    26,    19,   234,   216,   239,    20,    61,    21,   245,
    22,    27,    28,    23,   246,   253,    10,    24,   124,   104,
   158,    25,   163,     0,     0,     0,     0,    26,    16,   136,
     0,     0,    17,     0,    18,     0,    19,    27,    28,     0,
    20,     0,    21,     0,    22,     0,   136,    23,     0,   136,
   115,    24,     0,     0,    16,    25,     0,     0,    17,     0,
    18,    26,    19,   136,   136,     0,    20,     0,    21,     0,
    22,    27,    28,    23,     0,     0,     0,    24,     0,     0,
   119,    25,     0,     0,     0,     0,     0,    26,    16,     0,
     0,     0,    17,     0,    18,     0,    19,    27,    28,     0,
    20,     0,    21,     0,    22,    99,   186,    23,     0,     0,
     0,    24,     0,    44,     0,    25,     0,   100,   126,   101,
    47,    26,    16,     0,     0,     0,    17,     0,    18,     0,
    19,    27,    28,     0,    20,     0,    21,     0,    22,     0,
    16,    23,     0,     0,    17,    24,    18,     0,    19,    25,
     0,     0,    20,     0,    21,    26,    22,     0,   130,    23,
     0,     0,     0,    24,   160,    27,    28,    25,     0,     0,
     0,     0,     0,    26,    16,     0,     0,     0,    17,     0,
    18,     0,    19,    27,    28,     0,    20,     0,    21,     0,
    22,     0,    16,    23,     0,     0,    17,    24,    18,     0,
    19,    25,     0,     0,    20,     0,    21,    26,    22,     0,
     0,    23,    43,    91,   172,    24,    18,    27,    28,    25,
    44,     0,     0,     0,    45,    26,    46,    47,     0,     0,
     0,     0,     0,    16,   175,    27,    28,    17,     0,    18,
     0,    19,   191,     0,     0,    20,     0,    21,     0,    22,
     0,    16,    23,    27,    28,    17,    24,    18,     0,    19,
    25,     0,     0,    20,     0,    21,    26,    22,     0,     0,
    23,     0,     0,     0,    24,     0,    27,    28,    25,     0,
     0,     0,     0,   197,    26,    16,     0,     0,     0,    17,
     0,    18,     0,    19,    27,    28,     0,    20,     0,    21,
    53,    22,    43,     0,    23,    54,    18,     0,    24,     0,
    44,     0,    25,     0,    45,     0,    46,    47,    26,    43,
   145,     0,     0,    18,     0,     0,     0,    44,    27,    28,
     0,    45,     0,    46,    47,     0,     0,    43,     0,     0,
     0,    18,    43,    27,    28,    44,    18,     0,     0,    45,
    44,    46,    47,   183,    45,     0,    46,    47,     0,     0,
    27,    28,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    27,    28,
     0,     0,     0,    27,    28
};

static const short yycheck[] = {     6,
    13,   179,    17,    16,    17,    24,    18,   223,   180,    45,
     4,     3,     5,    20,    18,     7,   200,    24,    10,   170,
   171,    40,    41,   239,    31,    16,    17,   205,    43,     9,
    43,    22,    47,     9,    47,    42,   208,   221,    18,    22,
    53,     5,    18,    55,    56,     5,    29,    54,     7,   227,
    10,    58,    43,   237,    61,    46,    47,    11,   230,    66,
   211,    68,    53,    70,   100,    72,    73,    14,     5,    76,
    77,    78,     5,    80,    81,    22,   112,   228,    23,    26,
   231,    28,    29,    30,    99,    23,    99,    50,    51,    25,
    53,    98,    55,    56,   245,   246,    13,    14,    23,   106,
   107,    18,     5,     6,   111,    22,    29,    10,    99,    26,
   101,    28,    29,    17,   121,   122,   123,    13,    14,     5,
     6,    21,     3,     4,    10,   140,    22,   140,   135,    19,
    26,    38,    28,    29,    16,    17,    12,    34,    55,    56,
    16,    40,    18,   150,    20,    21,   153,   154,    24,   140,
    26,     5,    28,   160,    43,    31,    10,   164,   165,    35,
   167,    43,   169,    39,    42,    47,    48,    22,    40,    45,
    52,    53,    27,   180,   181,    57,    32,    33,    19,    55,
    56,    22,    13,    14,   191,     7,     8,   194,   195,    46,
    47,    22,    49,   200,    46,    26,    46,    28,    29,    49,
    82,   208,    50,    51,    48,    53,    49,    14,    36,    91,
    17,   218,    94,    95,   221,    22,   223,    99,   225,    26,
   102,    28,    29,   230,    55,    56,    11,    12,    55,    56,
   237,    16,   239,    18,    36,    20,    51,    14,    43,    24,
    52,    26,    50,    28,    53,    22,    31,    14,    15,    26,
    35,    28,    29,    30,    39,    22,    54,   139,   140,    26,
    45,    28,    29,   145,    50,   147,   148,    49,    12,    21,
    55,    56,    16,    43,    18,    44,    20,    36,    37,    41,
    24,    46,    26,    51,    28,    49,    43,    31,   170,   171,
    53,    35,    36,    37,    12,    39,    49,     0,    16,    50,
    18,    45,    20,    50,   186,    41,    24,    25,    26,    49,
    28,    55,    56,    31,    49,     0,     3,    35,    76,    53,
   117,    39,   123,    -1,    -1,    -1,    -1,    45,    12,   211,
    -1,    -1,    16,    -1,    18,    -1,    20,    55,    56,    -1,
    24,    -1,    26,    -1,    28,    -1,   228,    31,    -1,   231,
    34,    35,    -1,    -1,    12,    39,    -1,    -1,    16,    -1,
    18,    45,    20,   245,   246,    -1,    24,    -1,    26,    -1,
    28,    55,    56,    31,    -1,    -1,    -1,    35,    -1,    -1,
    38,    39,    -1,    -1,    -1,    -1,    -1,    45,    12,    -1,
    -1,    -1,    16,    -1,    18,    -1,    20,    55,    56,    -1,
    24,    -1,    26,    -1,    28,    14,    15,    31,    -1,    -1,
    -1,    35,    -1,    22,    -1,    39,    -1,    26,    42,    28,
    29,    45,    12,    -1,    -1,    -1,    16,    -1,    18,    -1,
    20,    55,    56,    -1,    24,    -1,    26,    -1,    28,    -1,
    12,    31,    -1,    -1,    16,    35,    18,    -1,    20,    39,
    -1,    -1,    24,    -1,    26,    45,    28,    -1,    48,    31,
    -1,    -1,    -1,    35,    36,    55,    56,    39,    -1,    -1,
    -1,    -1,    -1,    45,    12,    -1,    -1,    -1,    16,    -1,
    18,    -1,    20,    55,    56,    -1,    24,    -1,    26,    -1,
    28,    -1,    12,    31,    -1,    -1,    16,    35,    18,    -1,
    20,    39,    -1,    -1,    24,    -1,    26,    45,    28,    -1,
    -1,    31,    14,    15,    52,    35,    18,    55,    56,    39,
    22,    -1,    -1,    -1,    26,    45,    28,    29,    -1,    -1,
    -1,    -1,    -1,    12,    54,    55,    56,    16,    -1,    18,
    -1,    20,    21,    -1,    -1,    24,    -1,    26,    -1,    28,
    -1,    12,    31,    55,    56,    16,    35,    18,    -1,    20,
    39,    -1,    -1,    24,    -1,    26,    45,    28,    -1,    -1,
    31,    -1,    -1,    -1,    35,    -1,    55,    56,    39,    -1,
    -1,    -1,    -1,    44,    45,    12,    -1,    -1,    -1,    16,
    -1,    18,    -1,    20,    55,    56,    -1,    24,    -1,    26,
    12,    28,    14,    -1,    31,    17,    18,    -1,    35,    -1,
    22,    -1,    39,    -1,    26,    -1,    28,    29,    45,    14,
    15,    -1,    -1,    18,    -1,    -1,    -1,    22,    55,    56,
    -1,    26,    -1,    28,    29,    -1,    -1,    14,    -1,    -1,
    -1,    18,    14,    55,    56,    22,    18,    -1,    -1,    26,
    22,    28,    29,    30,    26,    -1,    28,    29,    -1,    -1,
    55,    56,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    55,    56,
    -1,    -1,    -1,    55,    56
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 57 "Parser.y"
{ cout<<yyvsp[0].value; ;
    break;}
case 2:
#line 58 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 3:
#line 59 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 4:
#line 60 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 5:
#line 61 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 6:
#line 62 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[0].value; ;
    break;}
case 7:
#line 63 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[0].value; ;
    break;}
case 8:
#line 64 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 9:
#line 65 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 10:
#line 68 "Parser.y"
{
				cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 11:
#line 70 "Parser.y"
{
			cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 12:
#line 74 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 13:
#line 75 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 14:
#line 78 "Parser.y"
{ cout<<yyvsp[0].value; ;
    break;}
case 15:
#line 79 "Parser.y"
{cout<<yyvsp[0].value<<" "; ;
    break;}
case 16:
#line 82 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 17:
#line 83 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 18:
#line 86 "Parser.y"
{ cout<<yyvsp[-1].value; ;
    break;}
case 19:
#line 87 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 20:
#line 88 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 21:
#line 89 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 22:
#line 90 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 23:
#line 91 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 24:
#line 92 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 25:
#line 93 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 26:
#line 94 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 27:
#line 95 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 28:
#line 96 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 29:
#line 97 "Parser.y"
{;
    break;}
case 30:
#line 98 "Parser.y"
{;
    break;}
case 31:
#line 99 "Parser.y"
{;
    break;}
case 32:
#line 102 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 33:
#line 103 "Parser.y"
{;
    break;}
case 34:
#line 106 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 35:
#line 109 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 36:
#line 110 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 37:
#line 111 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 38:
#line 112 "Parser.y"
{cout<<yyvsp[-3].value; ;
    break;}
case 39:
#line 113 "Parser.y"
{cout<<yyvsp[-5].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 40:
#line 114 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 41:
#line 115 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 42:
#line 116 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 43:
#line 119 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 44:
#line 120 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 45:
#line 123 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 46:
#line 124 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 47:
#line 125 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 48:
#line 126 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 49:
#line 127 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 50:
#line 128 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 51:
#line 129 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 52:
#line 130 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 53:
#line 131 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 54:
#line 132 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 55:
#line 133 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 56:
#line 134 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 57:
#line 137 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 58:
#line 138 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 59:
#line 139 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 60:
#line 140 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 61:
#line 143 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 62:
#line 144 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 63:
#line 145 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 64:
#line 146 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 65:
#line 149 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 66:
#line 150 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 67:
#line 151 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 68:
#line 152 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 69:
#line 155 "Parser.y"
{cout<<yyvsp[-5].value<<" "<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-1].value;;
    break;}
case 70:
#line 156 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 71:
#line 157 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "; ;
    break;}
case 72:
#line 158 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 73:
#line 159 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 74:
#line 160 "Parser.y"
{cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 75:
#line 161 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value;;
    break;}
case 76:
#line 162 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 77:
#line 165 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 78:
#line 166 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 79:
#line 167 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 80:
#line 168 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 81:
#line 169 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 82:
#line 170 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 83:
#line 173 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 84:
#line 174 "Parser.y"
{ cout<<yyvsp[-1].value; ;
    break;}
case 85:
#line 175 "Parser.y"
{ cout<<yyvsp[0].value; ;
    break;}
case 86:
#line 176 "Parser.y"
{;
    break;}
case 87:
#line 177 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 88:
#line 180 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 89:
#line 181 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 90:
#line 182 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 91:
#line 183 "Parser.y"
{cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 92:
#line 184 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 93:
#line 185 "Parser.y"
{;
    break;}
case 94:
#line 186 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 95:
#line 187 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 96:
#line 188 "Parser.y"
{;
    break;}
case 97:
#line 189 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 98:
#line 190 "Parser.y"
{;
    break;}
case 99:
#line 191 "Parser.y"
{ ;
    break;}
case 100:
#line 192 "Parser.y"
{ cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 101:
#line 193 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 102:
#line 194 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 103:
#line 195 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 104:
#line 196 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 105:
#line 197 "Parser.y"
{;
    break;}
case 106:
#line 198 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 107:
#line 199 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 108:
#line 200 "Parser.y"
{;
    break;}
case 109:
#line 201 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 110:
#line 202 "Parser.y"
{;
    break;}
case 111:
#line 205 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 112:
#line 206 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 113:
#line 209 "Parser.y"
{;
    break;}
case 114:
#line 210 "Parser.y"
{;
    break;}
case 115:
#line 213 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value;;
    break;}
case 116:
#line 214 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value;;
    break;}
case 117:
#line 215 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 118:
#line 218 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 119:
#line 219 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 120:
#line 222 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 121:
#line 223 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 122:
#line 226 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 123:
#line 227 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 124:
#line 228 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[0].value; ;
    break;}
case 125:
#line 229 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 126:
#line 230 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 127:
#line 231 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 128:
#line 232 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 129:
#line 233 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-1].value; ;
    break;}
case 130:
#line 234 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 131:
#line 235 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 132:
#line 238 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 133:
#line 239 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 134:
#line 242 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 135:
#line 243 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 136:
#line 244 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value;
    break;}
case 137:
#line 245 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 138:
#line 246 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 139:
#line 247 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 140:
#line 250 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 141:
#line 251 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 142:
#line 252 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 143:
#line 253 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 144:
#line 256 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 145:
#line 257 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 146:
#line 258 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 147:
#line 259 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 262 "Parser.y"

void yyerror(const char *msg){
	printf("%s\n",msg);
}

int main(int argc,char **argv){
	extern FILE *yyin;
	if(argc >= 2){
		if(!(yyin = fopen(argv[1],"r"))){
			printf("File Error");
			return 0;
		}
	}
	yyparse();
	return 0;
}  


