#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from Parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "Parser.y"

#include<bits/stdc++.h>
#include<stdio.h>
#include<string.h>

using namespace std;
int i=0;

extern int yylex();
extern void yyerror(const char*);


#line 15 "Parser.y"
typedef union{
	char* object;
	const char *value;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	DOCTYPE	258
#define	HTMLOP	259
#define	HTMLCL	260
#define	HEADOP	261
#define	HEADCL	262
#define	TITLEOP	263
#define	TITLECL	264
#define	BODYOP	265
#define	BODYCL	266
#define	BPHRASEOP	267
#define	BPHRASECL	268
#define	PHRASEOP	269
#define	PHRASECL	270
#define	GTPHOP	271
#define	GTPHCL	272
#define	TEXT	273
#define	AOPOP	274
#define	AOP	275
#define	ACL	276
#define	ATTRIBUTE	277
#define	ATTRIBUTEVAL	278
#define	DIVOP	279
#define	DIVCL	280
#define	IMGOP	281
#define	IMGCL	282
#define	FONTOP	283
#define	FONTOOP	284
#define	FONTCL	285


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int DOCTYPE;
static const int HTMLOP;
static const int HTMLCL;
static const int HEADOP;
static const int HEADCL;
static const int TITLEOP;
static const int TITLECL;
static const int BODYOP;
static const int BODYCL;
static const int BPHRASEOP;
static const int BPHRASECL;
static const int PHRASEOP;
static const int PHRASECL;
static const int GTPHOP;
static const int GTPHCL;
static const int TEXT;
static const int AOPOP;
static const int AOP;
static const int ACL;
static const int ATTRIBUTE;
static const int ATTRIBUTEVAL;
static const int DIVOP;
static const int DIVCL;
static const int IMGOP;
static const int IMGCL;
static const int FONTOP;
static const int FONTOOP;
static const int FONTCL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,DOCTYPE=258
	,HTMLOP=259
	,HTMLCL=260
	,HEADOP=261
	,HEADCL=262
	,TITLEOP=263
	,TITLECL=264
	,BODYOP=265
	,BODYCL=266
	,BPHRASEOP=267
	,BPHRASECL=268
	,PHRASEOP=269
	,PHRASECL=270
	,GTPHOP=271
	,GTPHCL=272
	,TEXT=273
	,AOPOP=274
	,AOP=275
	,ACL=276
	,ATTRIBUTE=277
	,ATTRIBUTEVAL=278
	,DIVOP=279
	,DIVCL=280
	,IMGOP=281
	,IMGCL=282
	,FONTOP=283
	,FONTOOP=284
	,FONTCL=285


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::DOCTYPE=258;
const int YY_parse_CLASS::HTMLOP=259;
const int YY_parse_CLASS::HTMLCL=260;
const int YY_parse_CLASS::HEADOP=261;
const int YY_parse_CLASS::HEADCL=262;
const int YY_parse_CLASS::TITLEOP=263;
const int YY_parse_CLASS::TITLECL=264;
const int YY_parse_CLASS::BODYOP=265;
const int YY_parse_CLASS::BODYCL=266;
const int YY_parse_CLASS::BPHRASEOP=267;
const int YY_parse_CLASS::BPHRASECL=268;
const int YY_parse_CLASS::PHRASEOP=269;
const int YY_parse_CLASS::PHRASECL=270;
const int YY_parse_CLASS::GTPHOP=271;
const int YY_parse_CLASS::GTPHCL=272;
const int YY_parse_CLASS::TEXT=273;
const int YY_parse_CLASS::AOPOP=274;
const int YY_parse_CLASS::AOP=275;
const int YY_parse_CLASS::ACL=276;
const int YY_parse_CLASS::ATTRIBUTE=277;
const int YY_parse_CLASS::ATTRIBUTEVAL=278;
const int YY_parse_CLASS::DIVOP=279;
const int YY_parse_CLASS::DIVCL=280;
const int YY_parse_CLASS::IMGOP=281;
const int YY_parse_CLASS::IMGCL=282;
const int YY_parse_CLASS::FONTOP=283;
const int YY_parse_CLASS::FONTOOP=284;
const int YY_parse_CLASS::FONTCL=285;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		117
#define	YYFLAG		-32768
#define	YYNTBASE	31

#define YYTRANSLATE(x) ((unsigned)(x) <= 285 ? yytranslate[x] : 44)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     6,     9,    14,    18,    24,    29,    34,    38,
    42,    45,    48,    52,    55,    57,    61,    64,    67,    70,
    73,    76,    79,    83,    86,    88,    90,    93,    97,   100,
   107,   112,   116,   122,   126,   129,   135,   140,   144,   147,
   150,   152,   157,   161,   165,   168,   170,   172,   177,   181,
   185,   188,   192,   195,   199,   202,   204,   207,   209,   213,
   215,   220,   226,   230,   235,   241
};

static const short yyrhs[] = {     3,
     0,     3,     4,     5,     0,     4,     5,     0,     3,     4,
    32,     5,     0,     4,    32,     5,     0,     3,     4,    32,
    35,     5,     0,     4,    32,    35,     5,     0,     3,     4,
    35,     5,     0,     4,    35,     5,     0,     6,    33,     7,
     0,     6,     7,     0,     8,     9,     0,     8,    34,     9,
     0,    34,    18,     0,    18,     0,    10,    36,    11,     0,
    10,    11,     0,    12,    40,     0,    16,    39,     0,    20,
    38,     0,    24,    37,     0,    26,    42,     0,    26,    42,
    36,     0,    28,    43,     0,    34,     0,    25,     0,    25,
    36,     0,    36,    25,    36,     0,    36,    25,     0,    22,
    23,    19,    36,    21,    36,     0,    19,    36,    21,    36,
     0,    19,    21,    36,     0,    22,    23,    19,    36,    21,
     0,    19,    36,    21,     0,    19,    21,     0,    22,    23,
    19,    21,    36,     0,    22,    23,    19,    21,     0,    41,
    17,    36,     0,    17,    36,     0,    41,    17,     0,    17,
     0,    12,    40,    17,    36,     0,    12,    40,    17,     0,
    41,    13,    36,     0,    13,    36,     0,    13,     0,    43,
     0,    41,    14,    41,    15,     0,    41,    14,    15,     0,
    14,    41,    15,     0,    14,    15,     0,    41,    26,    42,
     0,    41,    43,     0,    41,    28,    43,     0,    28,    43,
     0,    43,     0,    26,    42,     0,    34,     0,    22,    23,
    42,     0,    27,     0,    22,    23,    29,    30,     0,    22,
    23,    29,    41,    30,     0,    29,    41,    30,     0,    22,
    23,    29,    13,     0,    22,    23,    29,    41,    13,     0,
    29,    41,    13,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    50,    51,    53,    54,    56,    58,    60,    62,    64,    68,
    70,    73,    74,    77,    78,    81,    82,    85,    86,    87,
    88,    89,    90,    91,    92,    95,    96,    97,    98,   101,
   102,   103,   104,   105,   106,   107,   108,   111,   112,   113,
   114,   115,   116,   119,   120,   121,   122,   125,   126,   127,
   128,   129,   130,   131,   132,   133,   134,   135,   138,   139,
   142,   143,   144,   145,   146,   147
};

static const char * const yytname[] = {   "$","error","$illegal.","DOCTYPE",
"HTMLOP","HTMLCL","HEADOP","HEADCL","TITLEOP","TITLECL","BODYOP","BODYCL","BPHRASEOP",
"BPHRASECL","PHRASEOP","PHRASECL","GTPHOP","GTPHCL","TEXT","AOPOP","AOP","ACL",
"ATTRIBUTE","ATTRIBUTEVAL","DIVOP","DIVCL","IMGOP","IMGCL","FONTOP","FONTOOP",
"FONTCL","st","head","title","text","body","flow","div","atag","gtph","phraseopen",
"phrases","img","font",""
};
#endif

static const short yyr1[] = {     0,
    31,    31,    31,    31,    31,    31,    31,    31,    31,    32,
    32,    33,    33,    34,    34,    35,    35,    36,    36,    36,
    36,    36,    36,    36,    36,    37,    37,    37,    37,    38,
    38,    38,    38,    38,    38,    38,    38,    39,    39,    39,
    39,    39,    39,    40,    40,    40,    40,    41,    41,    41,
    41,    41,    41,    41,    41,    41,    41,    41,    42,    42,
    43,    43,    43,    43,    43,    43
};

static const short yyr2[] = {     0,
     1,     3,     2,     4,     3,     5,     4,     4,     3,     3,
     2,     2,     3,     2,     1,     3,     2,     2,     2,     2,
     2,     2,     3,     2,     1,     1,     2,     3,     2,     6,
     4,     3,     5,     3,     2,     5,     4,     3,     2,     2,
     1,     4,     3,     3,     2,     1,     1,     4,     3,     3,
     2,     3,     2,     3,     2,     1,     2,     1,     3,     1,
     4,     5,     3,     4,     5,     3
};

static const short yydefact[] = {     0,
     1,     0,     0,     3,     0,     0,     0,     0,     2,     0,
     0,    11,     0,     0,    17,     0,     0,    15,     0,     0,
     0,     0,    25,     0,     5,     0,     9,     4,     0,     8,
    12,     0,    10,    46,     0,     0,     0,     0,     0,    58,
    18,     0,    56,     0,    41,    19,     0,    56,     0,     0,
    20,    26,     0,    21,     0,    60,    22,    24,    14,    16,
     7,     6,    13,    45,    51,     0,     0,    57,    55,     0,
     0,     0,     0,     0,    53,     0,    39,    40,    35,     0,
     0,    27,    29,     0,    23,    50,     0,    66,    63,    44,
    49,     0,    52,    54,    43,    38,    32,    34,     0,    28,
    59,    64,    61,     0,    48,    42,    31,    37,     0,    65,
    62,    36,    33,    30,     0,     0,     0
};

static const short yydefgoto[] = {   115,
     7,    14,    23,     8,    24,    54,    51,    46,    41,    42,
    57,    75
};

static const short yypact[] = {    62,
    11,    67,   101,-32768,    73,    74,    64,    16,-32768,    77,
    22,-32768,    -1,    31,-32768,   159,    87,-32768,   -12,    29,
   -18,    14,    24,    33,-32768,    41,-32768,-32768,    43,-32768,
-32768,     2,-32768,   174,   191,    39,   -18,    14,   209,    24,
-32768,   182,     5,   159,   174,-32768,   219,-32768,   139,    61,
-32768,   174,    27,-32768,    66,-32768,   174,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   228,    68,-32768,-32768,   114,
   174,   200,   -18,    14,-32768,    78,-32768,   174,   174,    70,
    84,-32768,   174,   -18,-32768,-32768,   104,-32768,-32768,-32768,
-32768,   237,-32768,-32768,   174,-32768,-32768,   174,   150,-32768,
-32768,-32768,-32768,   124,-32768,-32768,-32768,   174,    75,-32768,
-32768,-32768,   174,-32768,   108,   110,-32768
};

static const short yypgoto[] = {-32768,
   109,-32768,   -11,    57,   -20,-32768,-32768,-32768,    76,   -16,
   -34,    -4
};


#define	YYLAST		266


static const short yytable[] = {    53,
    47,    32,    68,    55,    40,    40,    49,    31,    56,    50,
    63,    43,    48,    64,     3,   -47,    18,    58,    66,    59,
    27,   -47,    70,    40,    77,   -47,    30,    40,    80,   -47,
    48,    82,    40,    69,    48,    36,    85,    33,    93,    43,
    16,    59,    39,    60,    17,    61,    18,    62,    19,   101,
    90,    83,    20,    52,    21,    92,    22,    96,    97,    11,
    40,    67,   100,    26,     1,     2,    29,    48,    25,    94,
   104,     4,     5,     6,   106,    40,     6,   107,   109,    12,
    13,    28,    48,    81,    15,    16,     6,   112,    84,    17,
    98,    18,   114,    19,    95,   113,    87,    20,    44,    21,
    35,    22,    99,    45,    18,     9,     5,   116,    36,   117,
     6,    10,    37,     0,    38,    39,   102,    35,     0,    76,
     0,    18,     0,     0,     0,    36,    88,    72,     0,    37,
     0,    38,    39,   103,     0,    36,   110,    72,     0,    73,
     0,    74,    39,    89,     0,    36,     0,     0,     0,    73,
    16,    74,    39,   111,    17,     0,    18,     0,    19,    79,
     0,    16,    20,     0,    21,    17,    22,    18,     0,    19,
   108,    34,    35,    20,     0,    21,    18,    22,     0,     0,
    36,     0,     0,     0,    37,    16,    38,    39,     0,    17,
     0,    18,     0,    19,    71,    72,     0,    20,     0,    21,
     0,    22,     0,    36,    35,    65,     0,    73,    18,    74,
    39,     0,    36,    35,    91,     0,    37,    18,    38,    39,
     0,    36,    35,     0,     0,    37,    18,    38,    39,     0,
    36,     0,    72,     0,    37,    78,    38,    39,     0,     0,
    36,    72,    86,     0,    73,     0,    74,    39,     0,    36,
    72,   105,     0,    73,     0,    74,    39,     0,    36,     0,
     0,     0,    73,     0,    74,    39
};

static const short yycheck[] = {    20,
    17,    13,    37,    22,    16,    17,    19,     9,    27,    22,
     9,    16,    17,    34,     4,    11,    18,    22,    35,    18,
     5,    17,    39,    35,    45,    21,     5,    39,    49,    25,
    35,    52,    44,    38,    39,    22,    57,     7,    73,    44,
    12,    18,    29,    11,    16,     5,    18,     5,    20,    84,
    71,    25,    24,    25,    26,    72,    28,    78,    79,     3,
    72,    23,    83,     7,     3,     4,    10,    72,     5,    74,
    87,     5,     6,    10,    95,    87,    10,    98,    99,     7,
     8,     5,    87,    23,    11,    12,    10,   108,    23,    16,
    21,    18,   113,    20,    17,    21,    29,    24,    12,    26,
    14,    28,    19,    17,    18,     5,     6,     0,    22,     0,
    10,     3,    26,    -1,    28,    29,    13,    14,    -1,    44,
    -1,    18,    -1,    -1,    -1,    22,    13,    14,    -1,    26,
    -1,    28,    29,    30,    -1,    22,    13,    14,    -1,    26,
    -1,    28,    29,    30,    -1,    22,    -1,    -1,    -1,    26,
    12,    28,    29,    30,    16,    -1,    18,    -1,    20,    21,
    -1,    12,    24,    -1,    26,    16,    28,    18,    -1,    20,
    21,    13,    14,    24,    -1,    26,    18,    28,    -1,    -1,
    22,    -1,    -1,    -1,    26,    12,    28,    29,    -1,    16,
    -1,    18,    -1,    20,    13,    14,    -1,    24,    -1,    26,
    -1,    28,    -1,    22,    14,    15,    -1,    26,    18,    28,
    29,    -1,    22,    14,    15,    -1,    26,    18,    28,    29,
    -1,    22,    14,    -1,    -1,    26,    18,    28,    29,    -1,
    22,    -1,    14,    -1,    26,    17,    28,    29,    -1,    -1,
    22,    14,    15,    -1,    26,    -1,    28,    29,    -1,    22,
    14,    15,    -1,    26,    -1,    28,    29,    -1,    22,    -1,
    -1,    -1,    26,    -1,    28,    29
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 50 "Parser.y"
{ cout<<yyvsp[0].value; ;
    break;}
case 2:
#line 51 "Parser.y"
{
				cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 3:
#line 53 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 4:
#line 54 "Parser.y"
{ 
				       cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 5:
#line 56 "Parser.y"
{ 
				cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 6:
#line 58 "Parser.y"
{
					cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[0].value; ;
    break;}
case 7:
#line 60 "Parser.y"
{
				 cout<<yyvsp[-3].value<<" "<<yyvsp[0].value; ;
    break;}
case 8:
#line 62 "Parser.y"
{
				cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 9:
#line 64 "Parser.y"
{
				cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 10:
#line 68 "Parser.y"
{
				cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 11:
#line 70 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 12:
#line 73 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 13:
#line 74 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 14:
#line 77 "Parser.y"
{ cout<<yyvsp[0].value; ;
    break;}
case 15:
#line 78 "Parser.y"
{cout<<yyvsp[0].value<<" "; ;
    break;}
case 16:
#line 81 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 17:
#line 82 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 18:
#line 85 "Parser.y"
{ cout<<yyvsp[-1].value; ;
    break;}
case 19:
#line 86 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 20:
#line 87 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 21:
#line 88 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 22:
#line 89 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 23:
#line 90 "Parser.y"
{cout<<yyvsp[-2].value; ;
    break;}
case 24:
#line 91 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 25:
#line 92 "Parser.y"
{;
    break;}
case 26:
#line 95 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 27:
#line 96 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 28:
#line 97 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 29:
#line 98 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 30:
#line 101 "Parser.y"
{cout<<yyvsp[-5].value<<" "<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-1].value;;
    break;}
case 31:
#line 102 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 32:
#line 103 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "; ;
    break;}
case 33:
#line 104 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 34:
#line 105 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 35:
#line 106 "Parser.y"
{cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 36:
#line 107 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value;;
    break;}
case 37:
#line 108 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 38:
#line 111 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 39:
#line 112 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 40:
#line 113 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 41:
#line 114 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 42:
#line 115 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-1].value; ;
    break;}
case 43:
#line 116 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 44:
#line 119 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 45:
#line 120 "Parser.y"
{ cout<<yyvsp[-1].value; ;
    break;}
case 46:
#line 121 "Parser.y"
{ cout<<yyvsp[0].value; ;
    break;}
case 47:
#line 122 "Parser.y"
{;
    break;}
case 48:
#line 125 "Parser.y"
{ cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 49:
#line 126 "Parser.y"
{ cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 50:
#line 127 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 51:
#line 128 "Parser.y"
{cout<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 52:
#line 129 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 53:
#line 130 "Parser.y"
{;
    break;}
case 54:
#line 131 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 55:
#line 132 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 56:
#line 133 "Parser.y"
{;
    break;}
case 57:
#line 134 "Parser.y"
{cout<<yyvsp[-1].value; ;
    break;}
case 58:
#line 135 "Parser.y"
{;
    break;}
case 59:
#line 138 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[-1].value; ;
    break;}
case 60:
#line 139 "Parser.y"
{cout<<yyvsp[0].value; ;
    break;}
case 61:
#line 142 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value;;
    break;}
case 62:
#line 143 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value;;
    break;}
case 63:
#line 144 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 64:
#line 145 "Parser.y"
{cout<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[-1].value<<" "<<yyvsp[0].value; ;
    break;}
case 65:
#line 146 "Parser.y"
{cout<<yyvsp[-4].value<<" "<<yyvsp[-3].value<<" "<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
case 66:
#line 147 "Parser.y"
{cout<<yyvsp[-2].value<<" "<<yyvsp[0].value; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 150 "Parser.y"

void yyerror(const char *msg){
	printf("%s\n",msg);
}

int main(int argc,char **argv){
	extern FILE *yyin;
	if(argc >= 2){
		if(!(yyin = fopen(argv[1],"r"))){
			printf("File Error");
			return 0;
		}
	}
	yyparse();
	return 0;
}  


